    <footer class="mb-5">
        <nav class="navbar navbar-expand-lg bg-dark fixed-bottom">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse h5" id="navbarNavDropdown">
                    <ul id="footer" class="navbar-nav">
                        <a id="brandF" class="navbar-brand text-white mr-5 h3" href="../index.php">HappyFamily</a>
                            <li class="nav-item">
                                <a class="nav-link active text-white mr-4" aria-current="page" href="../index.php">Accueil</a>
                            </li>
                        <li class="nav-item">
                            <a class="nav-link text-white mr-4" href="../about.php">A propos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="../contact.php">Contact</a>
                        </li>
                    </ul>
                </div>
                <div id="cr" class="text-right col-3 mr-2 text-white h5"> Copyright &copy; 2021</div>
            </div>
        </nav>
    </footer>
</body>
</html>